// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO4SNfe3CxD_ZfBJv2osmjUynKqT35nns',
    appId: '1:72382502021:web:6b20932df095cd039205ec',
    messagingSenderId: '72382502021',
    projectId: 'feedpad-32991',
    authDomain: 'feedpad-32991.firebaseapp.com',
    storageBucket: 'feedpad-32991.firebasestorage.app',
    measurementId: 'G-24NYMZNH7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3qzQj5SVm-1P_jVgyI38_Nw276h9YRoY',
    appId: '1:72382502021:android:ef502619c1e2b5089205ec',
    messagingSenderId: '72382502021',
    projectId: 'feedpad-32991',
    storageBucket: 'feedpad-32991.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnmI-rw5aW9iuCGHiWoMjxPqfxIDY7318',
    appId: '1:72382502021:ios:d84f7e74c52ab2fa9205ec',
    messagingSenderId: '72382502021',
    projectId: 'feedpad-32991',
    storageBucket: 'feedpad-32991.firebasestorage.app',
    iosBundleId: 'com.example.feedpad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnmI-rw5aW9iuCGHiWoMjxPqfxIDY7318',
    appId: '1:72382502021:ios:d84f7e74c52ab2fa9205ec',
    messagingSenderId: '72382502021',
    projectId: 'feedpad-32991',
    storageBucket: 'feedpad-32991.firebasestorage.app',
    iosBundleId: 'com.example.feedpad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO4SNfe3CxD_ZfBJv2osmjUynKqT35nns',
    appId: '1:72382502021:web:f5bc1f088fabc1559205ec',
    messagingSenderId: '72382502021',
    projectId: 'feedpad-32991',
    authDomain: 'feedpad-32991.firebaseapp.com',
    storageBucket: 'feedpad-32991.firebasestorage.app',
    measurementId: 'G-1VXF1PBKJV',
  );
}
